Improvements to GOJA README file and the interface (new -ego option)
JPETTomography/j-pet-gate-tools pull request #19
Opened 2022-02-02 01:31 UTC by flukson

2022-02-02 01:32 UTC, flukson commented
@wkrzemien please review the PR

2022-02-07 12:03 UTC, wkrzemien commented on goja/README.md
> +2) Coincidences may be formed with raw hits (based on tree Hits), from GOJA-merged singles (based on tree Hits) or GATE-marged singles (based on tree HEsingles).
```suggestion
2) Coincidences may be formed with raw hits (based on tree Hits), from GOJA-merged singles (based on tree Hits) or GATE-merged singles (based on tree HEsingles).
```

2022-02-07 12:06 UTC, wkrzemien commented on goja/README.md
> +3) There are currently 3 modes of merging hits into singles in GOJA (may be set with a switch in the code):
```suggestion
3) There are currently 3 modes of merging hits into singles in GOJA (it may be set with a switch in the code):
```

2022-02-07 12:06 UTC, wkrzemien commented on goja/README.md
> +   d) kEnergyWinner: single takes time and position from the hit with highest energy.
``
```suggestion
   d) kEnergyWinner: single takes time and position from the hit with the highest energy.
```

2022-02-07 12:07 UTC, wkrzemien commented on goja/README.md
> +   c) kCentroidWinnerEnergyWeightedFirstTime: time of the single is set to time of the first merged hit, while the position of the single is set to mean value for merged hits weighted with the energi
```suggestion
   c) kCentroidWinnerEnergyWeightedFirstTime: time of the single is set to the time of the first merged hit, while the position of the single is set to mean value for merged hits weighted with the energies of these hits (default option),
```

2022-02-07 12:08 UTC, wkrzemien commented on goja/goja_manager.py
> +def analyze_simulations_on_cluster(path_gate_output, single_file_prefix, path_goja_output, splits, eth, eth0, tw, N0, ego):
What does ego stand for?

2022-02-07 12:08 UTC, wkrzemien commented on goja/goja_manager.py
> +def analyze_simulations_on_cluster(path_gate_output, single_file_prefix, path_goja_output, splits, eth, eth0, tw, N0, ego):
a oki :)

2022-02-07 12:09 UTC, wkrzemien requested changes
Nice work! Small suggestions added

2022-02-14 09:03 UTC, wkrzemien approved these changes

2022-02-14 09:03 UTC, merged