[WIP] Improvements to GOJA + debugging coincidences
JPETTomography/j-pet-gate-tools pull request #22
Opened 2022-05-06 06:31 UTC by flukson

2022-05-06 07:41 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +    std::cout << max_index << std::endl;
Please, remove it

2022-05-06 07:44 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +void print_coincidence(const Hit h1, const Hit h2) {
```suggestion
void print_coincidence(const Hit& h1, const Hit& h2) {
```
see e.g.

2022-05-06 07:47 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +  std::cout << single1.posX << " " << single1.posY << " " << single1.posZ << " " << std::endl;
change the couts to assertions, 
we want that the test breaks if the assertion is not fullfiled

2022-05-06 07:51 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +    for (unsigned int i = 0; i<nHits; i++) energies.push_back(hits[i].edep);
So it was the bug at the end, cause this line was commented in your code. and the kEnergyWinner was not returning the sum

2022-05-06 08:00 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +    singles.push_back(merge_hits(it_tmp->second, AveragingMethod(int(atof(getenv("GOJA_AVERAGING_METHOD"))))));
I don't like mixing getenv within the body of the function. You are effectively introducing global variables and adding dependencies. E.g. I cannot call select_coincident_singles without setting this variable. All those getenvs should be ideally called in one place.
`auto averaging_type =AveragingMethod(int(atof(getenv("GOJA_AVERAGING_METHOD")` should be called in the analyse_event method. Next, you can send it as  an additional argument to select_coincident_singles which corresponds to the averaging type and pass it to the function.
e.g. `std::tuple<int, int, std::vector<Hit>>  select_coincident_singles(const std::vector<Hit> &hits, double compton_energy_threshold, AveragingMethod  averagingMethod = kCentroidWinnerEnergyWeightedFirstTime)`

2022-05-06 08:01 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +    singles.push_back(merge_hits(it_tmp->second, AveragingMethod(int(atof(getenv("GOJA_AVERAGING_METHOD"))))));
or even:
`std::tuple<int, int, std::vector<Hit>> select_coincident_singles(const std::vector<Hit> &hits, double compton_energy_threshold, const std::string& systemType, AveragingMethod averagingMethod = kCentroidWinnerEnergyWeightedFirstTime)`

2022-05-06 08:03 UTC, wkrzemien requested changes
Nice work. Some comments added.

2022-05-24 06:19 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +  //if (N>=2 and N<=MAX_N and N0<=MAX_N0) print_coincidences(selected_hits);
Please, remove this commented code

2022-05-24 06:21 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +  //std::cout << single1.time << " " << single1.posX << " " << single1.posY << " " << single1.posZ << " " << std::endl;
Please, remove those commented lines. And those below as well

2022-05-24 06:23 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +  assert(std::abs(single2.posX-3.714285714) < epsilon);
could you also add the assertion about the expected energy value for all the cases?

2022-05-24 06:25 UTC, wkrzemien reviewed
Very nice! I have only a few tiny comments. mainly to remove the commented code and add explicitly expected values for the energy in tests

2022-05-24 06:28 UTC, flukson commented on goja/EventAnalysis.cpp
> +  //if (N>=2 and N<=MAX_N and N0<=MAX_N0) print_coincidences(selected_hits);
I would leave it for now. Maybe it should be discussed and modified or just for this moment provided as the option.

2022-06-14 07:06 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +  //cout << verify_type_of_coincidence(h1, h2) << "\t";
please, remove this line

2022-06-14 07:07 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +  //if (N>=2 and N<=MAX_N and N0<=MAX_N0) print_coincidences(selected_hits);
ok

2022-06-14 07:09 UTC, wkrzemien requested changes
Very small comments added. Also, check why tests are not passing

2022-07-18 10:16 UTC, acoussat commented on goja/EventAnalysis.cpp
> +  assert(std::abs(single1.posX-3.333333333) < epsilon);
Perhaps it would be useful for future reference to indicate (using either comments or variables) what the values `22`, `3.333333333`, etc. correspond to, like it was done on the line below?

2022-07-18 10:28 UTC, acoussat reviewed
Looks good to me, compiles and seems to run fine on my computer.

2022-07-27 08:08 UTC, wkrzemien commented
I am merging it to develop

2022-07-27 08:08 UTC, merged