Update to include triple coincidences
JPETTomography/j-pet-gate-tools pull request #25
Opened 2023-01-12 10:12 UTC by sparzych

2023-02-07 18:42 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +std::tuple<bool, std::vector<Hit>> check_if_2plus1(const std::vector<Hit>& hits)
Not the best name of the function. Maybe e.g. `get_2plus1_if_present()`

2023-02-07 18:50 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +  }
A bit modern way would be
```suggestion
  for (auto hit&: hits )
  {
    if (hit.edep <= COMPTON_E_TH_PROMPT)
    {
      triple_hits.push_back(hit);
    }
  }
```

2023-02-07 18:53 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +  for (unsigned int i = 0; i < hits.size(); i++)
Maybe I misunderstood the logic, but why do you need to go twice over hits?
you cannot do if else ?

2023-02-07 18:56 UTC, wkrzemien commented on goja/goja.cpp
> +  SET_GOJA_ENV_VAR("eth-prompt", "GOJA_COMPTON_E_TH_PROMPT", "0.35");
what happens if this parameter is not set? We don't need it for the two photon case right?

2023-02-07 18:56 UTC, wkrzemien requested changes
Nice work. Just a few suggestions

2023-02-10 11:44 UTC, sparzych commented on goja/EventAnalysis.cpp
> +std::tuple<bool, std::vector<Hit>> check_if_2plus1(const std::vector<Hit>& hits)
Done

2023-02-10 11:45 UTC, sparzych commented on goja/EventAnalysis.cpp
> +  for (unsigned int i = 0; i < hits.size(); i++)
The idea was to have prompts at then end of vector and annihilation gammas at the beginning. Now however, it is changed to assign corresponding photons to different vectors and then join them

2023-02-10 11:45 UTC, sparzych commented on goja/EventAnalysis.cpp
> +  }
Done

2023-02-10 11:50 UTC, sparzych commented on goja/goja.cpp
> +  SET_GOJA_ENV_VAR("system-type", "GOJA_SYSTEM_TYPE", "cylindricalPET");
Since in simulations we are using no mostly the cylindricalPET type of the system, and the coincidence printing functions are not working properly with other system type (both double coincidence printing funtion from original code and new tripe coincidence function is printing inofmrations like "rsectorID" which is not obtained from inputed tree unless the system is of type "cylindricalPET"), I decided to change the default system to "cylindricalPET"

2023-02-15 09:33 UTC, wkrzemien commented on goja/EventAnalysis.cpp
> +std::tuple<bool, std::vector<Hit>> get_2plus1_if_present(const std::vector<Hit>& hits)
```suggestion
std::tuple<bool, std::vector<Hit>> get_2plus1_if_present(const std::vector<Hit>& hits, double compton_e_th_prompt)
```

2023-02-21 15:36 UTC, merged